create table travel_spots
(
    id       number generated by default on null as identity primary key,
    name     varchar2(100 char) not null,
    location varchar2(300 char) not null,
    season   varchar2(10 char) not null check (season in ('SPRING', 'SUMMER', 'FALL', 'WINTER')),
    rating   number(2, 1) default 0 check (rating >= 0 and rating <= 5)
);

insert into travel_spots (name, location, season, rating)
values ('제주도 우도', '제주특별자치도 제주시 우도면', 'SPRING', 4.8),
       ('경주 보문호수', '경상북도 경주시 보문로 424', 'SPRING', 4.6),
       ('속초 해수욕장', '강원도 속초시 조양동', 'SUMMER', 4.7),
       ('부산 해운대', '부산광역시 해운대구 중동', 'SUMMER', 4.9),
       ('남이섬', '강원도 춘천시 남산면', 'FALL', 4.8),
       ('설악산 국립공원', '강원도 속초시 설악산로', 'FALL', 4.5),
       ('정동진 해변', '강원도 강릉시 정동진리', 'WINTER', 4.3),
       ('대관령 양떼목장', '강원도 평창군 대관령면', 'WINTER', 4.7),
       ('여수 오동도', '전라남도 여수시 오동도로', 'SPRING', 4.2),
       ('강릉 안목해변', '강원도 강릉시 창해로', 'SUMMER', 4.6);
