create table videos
(
    id          number generated by default on null as identity primary key,
    title       varchar2(100 char) not null,
    channel     varchar2(100 char) not null,
    upload_date date not null,
    views       number default 0 check (views >= 0),
    likes       number default 0 check (likes >= 0)
);

-- 테스트용 더미 영상 데이터
insert into videos (title, channel, upload_date, views, likes)
values ('dummy_video_1', 'dummy_channel_1', SYSDATE, 0, 1),
       ('dummy_video_2', 'dummy_channel_1', SYSDATE, 1, 1),
       ('dummy_video_3', 'dummy_channel_2', SYSDATE, 0, 3),
       ('dummy_video_4', 'dummy_channel_2', SYSDATE, 4, 1),
       ('dummy_video_5', 'dummy_channel_3', SYSDATE, 5, 1);
